CREATE DATABASE sa_ferrorama;
USE sa_ferrorama;

CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    telefone VARCHAR(15) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE TRENS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    localizacao VARCHAR(200) NOT NULL,
    tipo_de_dado VARCHAR(200) NOT NULL,
    status VARCHAR(200) NOT NULL
);

CREATE TABLE SENSORES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    localizacao VARCHAR(200) NOT NULL,
    tipo_de_dado VARCHAR(200) NOT NULL,
    trens_id INT NOT NULL,
    FOREIGN KEY (trens_id) REFERENCES TRENS(id) ON DELETE CASCADE
);

